version: 2.1

jobs:
  #
  # Release
  #
  release-version-with-changelog:
    machine:
      image: ubuntu-1604:201903-01 # Ubuntu 16.04, docker 18.09.3, docker-compose 1.23.1

      # This job has been blocked because Docker Layer Caching is not available on your plan.
      # Please upgrade to continue building.
      # Note: you will need to push a new commit or call the API to rerun the pipeline.
      docker_layer_caching: false

    environment:
      VERSION_NUMBER: patch # opts: patch, minor or major.

    steps:
      - checkout

      - run:
          name: Context Info Cmds
          command: pwd && ls -ltra && git branch

      - run:
          name: Initialize Repo Makefiles
          command: |
            make init-makefiles
            git update-index --assume-unchanged "Makefile"

      - run:
          name: Release New Version
          command: |
            if git status | grep 'nothing to commit, working tree clean'; then
              echo "==============================================================================================="
              echo "release-$VERSION_NUMBER-with-changelog-circleci"
              echo "==============================================================================================="
              git config --global user.email "$GIT_USER_EMAIL"
              git config --global user.name "$GIT_USER_NAME"
              make release-$VERSION_NUMBER-with-changelog-circleci
            else
              echo "==============================================================================================="
              echo "Changes in working directory pending to be pushed - please check 'git status' cmd output below "
              echo "==============================================================================================="
              echo "$(git status)"
              echo "==============================================================================================="
            fi

#
# Jobs workflow
#
workflows:
  version: 2
  test_and_release:
    jobs:
      - release-version-with-changelog:
          context: binbashar-org-global-context
          filters:
            branches:
             only: # only branches matching the below regex filters will run
               - master
