version: 2.1

jobs:
  #
  # Release
  #
  release-patch-with-changelog:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true

    steps:
      - checkout

      - run: pwd
      - run: ls -ltra
      - run: git branch

      - run:
          name: release-patch-with-changelog-circleci
          command: |
            if git status | grep 'nothing to commit, working tree clean'; then
              echo "==============================================================================================="
              echo "release-patch-with-changelog-circleci"
              echo "==============================================================================================="
              git config --global user.email "$GIT_USER_EMAIL"
              git config --global user.name "$GIT_USER_NAME"
              make release-patch-with-changelog-circleci
            else
              echo "==============================================================================================="
              echo "Changes in working directory pending to be pushed - please check 'git status' cmd output below "
              echo "==============================================================================================="
              echo "$(git status)"
              echo "==============================================================================================="
            fi
#
# Jobs workflow
#
workflows:
  version: 2
  changelog_and_release:
    jobs:
      - release-patch-with-changelog:
          context: binbashar-org-global-context
          filters:
            branches:
             only: # only branches matching the below regex filters will run
               - master